### ISSUE TITLE
Control Time Tab in Magellan from Python

### ISSUE THREAD

**Issue by kdmarchuk** [henrypinkard/Pygellan#10]
Hi Henry, 

I'd like to be able to control the time tab in Magellan through Python. Will need to be able to set whether the grids are run sequentially or not.

Thanks,
Kyle

**Comment by henrypinkard** [comment]
Hey working on adding these now. They are all straightforward, except I dont understand what you mean by "grids run sequentially or not". Maybe you could explain a bit more about what you're trying to do

**Comment by kdmarchuk** [comment]
If you're trying to do multiple ROIs, but also want increased time resolutions you may run you ROIs in order 1,1,1,2,2,2,3,3,3 instead of 1,2,3,1,2,3,1,2,3.

Maybe it is or isn't useful. Depends on if it's easy to implement.

**Comment by henrypinkard** [comment]
Okay, added control of Magellan GUI. 

Everything you need should be here: https://github.com/henrypinkard/Pygellan/blob/master/examples/control_magellan_gui.py

Also, I changed the functions from the java convention of camelCase() to the python one of functions_with_underscores() so if you've written old scripts you will need to change.

If in using this, you write scripts that would be good to add to examples, feel free to add them through pull requests (I can guide you through this if you've not done it before)

New features are available in pygellan 0.0.5 (update through pip) and on micro-manager side in next nightly build after this (https://github.com/nicost/micro-manager/pull/70) gets merged and built
