### ISSUE TITLE
Python Grid Setup

### ISSUE THREAD

**Issue by kdmarchuk** [henrypinkard/Pygellan#14]
Hi Henry, 

Thanks for the GUI access. It seems very straightforward. 

I'd like to be able to create Magellan grids using predefined positions. For example, `new_grid_1 = create_magellan_grid(xPos, yPos, nRows, nColumns)`

This will be essential for the randomized ROI acquisition interface I'm making.

Thanks for the help!
Kyle

**Comment by henrypinkard** [comment]
Forgot to add the example of this before:

 https://github.com/henrypinkard/Pygellan/blob/master/examples/grids_and_surfaces.py

There's just create right now, but let me know what other functionality you want in the API, it's straightforward to add

**Comment by kdmarchuk** [comment]
You work fast. Awesome!
