### ISSUE TITLE
setting the channel group via API doesn't update explorer GUI

### ISSUE THREAD

**Issue by tlnagy** [henrypinkard/Pygellan#18]
Latest master on both micromanager (nico's branch) and pygellan.

Running

```python
from pygellan.acquire import MagellanBridge
import os

#establish communication with Magellan
bridge = MagellanBridge()
#get object representing micro-magellan API
magellan = bridge.get_magellan()

acquistions = magellan.get_acquisitions()
#grab the first acquisition in the list
acq = acquistions[0]
acq_settings = acq.get_acquisition_settings()

#channel settings
acq_settings.set_channel_group('Channel')
```

<img width="587" alt="image" src="https://user-images.githubusercontent.com/1661487/64821470-c8e04700-d567-11e9-87f6-19f1013f25cd.png">

**Comment by henrypinkard** [comment]
Hey @tlnagy, I think I confused myself here. This is the explore channel group, not the acquisition channel group, so it actually shouldn't be updated.

BTW, I have put a lot of effort into redesigning the Magellan image viewer window. Available in next micro-manager gamma build after Nico merges this (https://github.com/nicost/micro-manager/pull/74). This should make it fairly straightforward to add support for imaging multi-well plates, if you're still interested in that.
