### ISSUE TITLE
Commands for deleting acquisitions and surfaces and grids

### ISSUE THREAD

**Issue by kdmarchuk** [henrypinkard/Pygellan#24]
It seems necessary for ensuring you're working with a fresh slate.

Thanks

**Comment by henrypinkard** [comment]
done.

https://github.com/nicost/micro-manager/pull/84

https://github.com/henrypinkard/Pygellan/blob/master/examples/grids_and_surfaces.py

**Comment by henrypinkard** [comment]
Adding something besides `delete_acquisition(index)` is a little weird because technically there needs to be one active acquisition at all times.

But if there's a better behavior I'm open to suggestions
