### ISSUE TITLE
Micro Manager Explore Z settings

### ISSUE THREAD

**Issue by BIDCatUCSF** [henrypinkard/Pygellan#7]
Hi Henry, 

When launching the explore window Magellan no longer sets the z limits to both be the current stage setting. It will set the lower limit to zero, which if you miss changing, will crash your stage (did it twice). Can you set it back to launch at the current setting?

Thanks,
Kyle

![MagellanSPIM](https://user-images.githubusercontent.com/26391996/63193195-aa973200-c021-11e9-89e9-5d93d2425839.png)

**Comment by henrypinkard** [comment]
Fixed with https://github.com/nicost/micro-manager/pull/63
